# Generated by Django 6.0.6 on 2026-07-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoimagen',
            name='url_externa',
            field=models.URLField(blank=True, verbose_name='URL externa (fallback para producción)'),
        ),
    ]
