# Generated by Django 6.0.6 on 2026-07-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_vendedor_alter_producto_existencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('general', 'General'), ('gastronomico', 'Gastronómico'), ('digital', 'Digital'), ('libro', 'Libro'), ('domestico', 'Doméstico'), ('servicio', 'Servicio'), ('inmueble', 'Inmueble'), ('vehiculo', 'Vehículo'), ('evento', 'Evento'), ('empleo', 'Empleo'), ('arte', 'Arte / Música')], default='general', max_length=20),
        ),
    ]
