# Generated by Django 6.0.6 on 2026-07-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_actualizado_producto_creado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
