# Generated by Django 6.0.6 on 2026-07-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadatos extra (autor, género, etc.)'),
        ),
    ]
