# Generated by Django 6.0.6 on 2026-07-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoimagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
