# Generated by Django 6.0.6 on 2026-07-13 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_libros', '0003_migrate_libros_to_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='libros',
            name='editora',
        ),
        migrations.RemoveField(
            model_name='libros',
            name='genero',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Editora',
        ),
        migrations.DeleteModel(
            name='Generos',
        ),
        migrations.DeleteModel(
            name='Libros',
        ),
    ]
