# Generated by Django 6.0.6 on 2026-07-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_profile_avatar_profile_nombre_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='super_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Super Admin ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grado',
            field=models.CharField(choices=[('v00', 'v00 - Desarrollador'), ('v1', 'v1 - Super Admin'), ('v2', 'v2 - Moderador'), ('v3', 'v3 - Proveedor'), ('v4', 'v4 - Comprador')], default='v4', max_length=3),
        ),
    ]
