# Generated by Django 6.0.6 on 2026-07-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_assign_super_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grado',
            field=models.CharField(choices=[('g0', 'g0 - Desarrollador'), ('v1', 'v1 - Super Admin'), ('v2', 'v2 - Moderador'), ('v3', 'v3 - Proveedor'), ('v4', 'v4 - Comprador')], default='v4', max_length=3),
        ),
    ]
