# Generated by Django 6.0.6 on 2026-07-13 07:18

import apps.usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_assign_super_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grado',
            field=models.CharField(choices=apps.usuarios.models._grado_choices, default='v4', max_length=3),
        ),
    ]
