# Generated by Django 6.0.6 on 2026-07-10 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_verificationcode_intentos_fallidos_loginattempt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='usuarios_lo_ip_addr_03d7f2_idx',
            old_name='usuarios_log_ip_addr_9ace5d_idx',
        ),
    ]
